language: objective-c
osx_image: xcode7.3
install:
  - gem install bundler
  - bundle install
script:
  - bundle exec podspec
  - gem install podspec --pre
after_script:
  - bundle exec podspec postmates/PMJSON
  - cat PMJSON.podspec
  - pod spec lint PMJSON.podspec --verbose
